In [1]:
# This section deals with the numpy assingment
import numpy as np

# task 1
oneD_array = np.arange(1,10)
print(oneD_array)

[1 2 3 4 5 6 7 8 9]


In [2]:
# task 2
basicD_array = np.array([True]*9)
threeD_array = basicD_array.reshape(3,3)
print(threeD_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
# task 3
print(oneD_array[::2])

[1 3 5 7 9]


In [4]:
# task 4
oneD_array = np.where(oneD_array%2==1, -1, oneD_array)
#print(test_array)
print(oneD_array)

[-1  2 -1  4 -1  6 -1  8 -1]


In [5]:
# task 5
convert_array = np.arange(1,11).reshape(2,5)
print(convert_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
# task 6
a = np.arange(0,9)
b = np.arange(0,9)
c = np.vstack((a,b))
d = np.sum(c)
e = np.dot(a,b)
print(c)
print(d)
print(e)

[[0 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]
72
204


In [7]:
# task 6.1
#concat_array = np.array()
for i in range (1,4):
    myarray = np.array([i,i,i])
    if i ==1:
        concat_array = myarray
    else:
        concat_array = np.concatenate((concat_array, myarray), axis = None)
temp_array = np.arange(1,4)
part_two_array = np.hstack((temp_array,temp_array,temp_array))
concat_array = np.concatenate((concat_array, part_two_array), axis = None)
print(concat_array)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [8]:
# task 6.2
a = np.arange(1,6)
b = np.arange(4,9)
a = np.setdiff1d(a, np.intersect1d(a,b))
print(a)

[1 2 3]


In [9]:
# task 6.3
a = np.arange(1,6)
b = np.arange(4,9)
c = np.concatenate((a,b), axis=None)
c = c[c>=3]
c = c[c<=7]
d = np.sum(c, axis=0)
print(c)
print(d)

[3 4 5 4 5 6 7]
34
